Password_manager/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, session
from flask_login import login_required, current_user, login_user
from .auth import get_otp, check_otp
from .models import Note, User
from . import db
from .models import PassList
import requests
import hashlib
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from wtforms.widgets import TextArea
from twilio.rest import Client
import phonenumbers

views = Blueprint('views', __name__)


# Adding Notes

@views.route('/add-notes', methods=['GET', 'POST'])
@login_required
def add_notes():
    if request.method == 'POST':
        note1 = request.form.get('note')
        title1 = request.form.get('title')
        print(note1)
        if len(note1) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note1, title=title1, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')
            notes = Note.query.order_by(Note.date)
            return render_template("notes.html", notes=notes, user=current_user)
    return render_template("add_note.html", user=current_user)


# Displaying the notes

@views.route('/notes', methods=['GET', 'POST'])
@login_required
def notes():
    notes = Note.query.order_by(Note.date)
    return render_template("notes.html", notes=notes, user=current_user)


# Displaying Single Notes in a page

@views.route('/notes/<int:id>', methods=['GET', 'POST'])
@login_required
def note(id):
    note_id = Note.query.get_or_404(id)
    return render_template('note.html', note_id=note_id, user=current_user)


# Editing the Notes

@views.route('/notes/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_note(id):
    form = PostForm()
    note_id = Note.query.get_or_404(id)
    if form.validate_on_submit():
        note_id.title = form.title.data
        note_id.data = form.data.data
        db.session.add(note_id)
        db.session.commit()
        flash("Data Updated", category='success')
        return redirect(url_for('views.note', id=note_id.id))
    form.title.data = note_id.title
    form.data.data = note_id.data
    return render_template('edit_note.html', form=form, user=current_user)


# Deleting the Notes

@views.route('/notes/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_note(id):
    note_id = Note.query.get_or_404(id)
    try:
        db.session.delete(note_id)
        db.session.commit()
        flash("Notes Deleted Succefully", category='success')
        notes = Note.query.order_by(Note.date)
        return render_template("notes.html", notes=notes, user=current_user)
    except:
        flash("Their was an Problem deleting", category='error')
        notes = Note.query.order_by(Note.date)
        return render_template("notes.html", notes=notes, user=current_user)


# Adding Password

@views.route('/addpass', methods=['GET', 'POST'])
@login_required
def addpass():
    if request.method == "POST":
        web = request.form.get('url')
        name = request.form.get('username')
        password = request.form.get('psw')
        if len(web) < 2:
            flash('The Name Of The Website Too Short!.', category='error')
        elif len(name) < 4:
            flash('Enter a valid email id.', category='error')
        elif len(password) < 8:
            flash('Password must be at least 8 characters.', category='error')
        else:
            pass_list = PassList(email=name, website=web, password=password, user_id=current_user.id)
            db.session.add(pass_list)
            db.session.commit()
            flash('Password Added!', category='success')
            passlist1 = PassList.query.order_by(PassList.date)
            return redirect(url_for('views.password'))
    return render_template("addpass.html", user=current_user)


# Displaying the Passwords

@views.route('/password')
@login_required
def password():
    Password = PassList.query.order_by(PassList.date)
    return render_template("password.html", user=current_user, Password=Password)


# Updating the Passwords

@views.route('/password/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update(id):
    name_to_update = PassList.query.get_or_404(id)
    if request.method == "POST":
        name_to_update.website = request.form['website']
        name_to_update.email = request.form['email']
        name_to_update.password = request.form['password']
        try:
            # db.session.add(name_to_update)
            db.session.commit()
            flash("Data Edited", category='success')
            return redirect(url_for('views.password'))
        except:
            flash("Error!", category='error')
            return render_template('update.html', name_to_update=name_to_update, user=current_user)
    else:
        return render_template("update.html", name_to_update=name_to_update, user=current_user)


# Deleting PassWords

@views.route('/password/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_password(id):
    password_id = PassList.query.get_or_404(id)
    try:
        db.session.delete(password_id)
        db.session.commit()
        flash("Password Deleted Succefully", category='success')
        Password = PassList.query.order_by(PassList.date)
        return redirect(url_for('views.password'))
    except:
        flash("Their was an Problem deleting", category='error')
        Password = PassList.query.order_by(PassList.date)
        return redirect(url_for('views.password'))


# Checking the Passwords

@views.route('/check', methods=['GET', 'POST'])
@login_required
def check():
    if request.method == "POST":
        password = request.form.get('password')
        password1 = password.encode()
        sha_password = hashlib.sha1(password1).hexdigest()
        sha_prefix = sha_password[0:5]
        sha_postfix = sha_password[5:].upper()
        url = "https://api.pwnedpasswords.com/range/" + sha_prefix
        payload = {}
        headers = {}
        response = requests.request("GET", url, headers=headers, data=payload)
        pwnd_list = response.text.split("\r\n")

        for pwnd_pass in pwnd_list:
            pwnd_hash = pwnd_pass.split(":")
            if len(pwnd_hash) >= 2:
                if sha_postfix == pwnd_hash[0]:
                    count = pwnd_hash[1]
                    flash(f"Your password has been found {count} times", category='error')
                    return redirect(url_for('views.check'))
        
        flash("Your password is safe!", category='success')

    return render_template("check.html", user=current_user)



# @views.route('/delete', methods=['POST'])
# @login_required
# def delete():
#     password = json.loads(request.data)
#     passId = password['passId']
#     password = PassList.query.get(passId)
#     print(password)
#     if password:
#         if password.user_id == current_user.id:
#             db.session.delete(password)
#             db.session.commit()
#
#     return jsonify({})


@views.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    all_data = User.query.all()
    # db.session.delete(all_data)
    # db.session.commit()
    # flash("Deleted User",category='success')
    return render_template("index.html", user=current_user, users=all_data)


@views.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@views.route('/home')
@login_required
def home():
    all_data = User.query.all()
    return render_template("home.html", user=current_user, users=all_data)


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    data = StringField("Data", validators=[DataRequired()], widget=TextArea())
    submit = SubmitField("Submit")


class Enable2faForm(FlaskForm):
    verification_phone = StringField('Phone', validators=[DataRequired()])
    submit = SubmitField('Enable 2FA')

    def validate_verification_phone(self, verification_phone):
        try:
            p = phonenumbers.parse(verification_phone.data)
            if not phonenumbers.is_valid_number(p):
                raise ValueError()
        except (phonenumbers.phonenumberutil.NumberParseException, ValueError):
            flash("Invalid Phone Number!", category='error')


@views.route('/enable_2fa', methods=['GET', 'POST'])
@login_required
def enable_2fa():
    form = Enable2faForm()
    if form.validate_on_submit():
        session['phone'] = form.verification_phone.data
        get_otp(session['phone'])
        return redirect(url_for('views.verify_2fa'))
    return render_template('enable2fa.html', form=form,user=current_user)


class Confirm2faForm(FlaskForm):
    token = StringField('Token')
    submit = SubmitField('Verify')

@views.route('/verify_2fa', methods=['GET', 'POST'])
def verify_2fa():
    form = Confirm2faForm()
    if form.validate_on_submit():
        phone = session['phone']
        if check_otp(phone, form.token.data):
            del session['phone']
            if current_user.is_authenticated:
                current_user.phone_no = phone
                db.session.commit()
                flash('Two-factor authentication is now enabled')
                return redirect(url_for('views.home'))
            else:
                username = session['username']
                del session['username']
                user = User.query.filter_by(email=username).first()
                login_user(user,remember=True)
                return render_template('home.html',user=current_user)
        flash("Invalid OTP",category='error')
    return render_template('verify_2fa.html', form=form,user=current_user)



class Disable2faForm(FlaskForm):
    submit = SubmitField('Disable 2FA')
    
from flask_login import current_user, login_required

class Disable2faForm(FlaskForm):

Password_manager/website/templates/add_note.html
{#{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content#}
{#%}#}
{#<h1 align="center">SecureNotes</h1>#}
{#<ul class="list-group list-group-flush" id="notes">#}
{#  {% for note in user.notes %}#}
{#  <li class="list-group-item">#}
{#    {{ note.data }}#}
{#    <button type="button" class="close" onClick="deleteNote({{ note.id }})">#}
{#            <a href="/edit/{{note.id}}" class="btn btn-secondary btn-sm">Edit</a>#}
{#      <span aria-hidden="true">&times;</span>#}
{#    </button>#}
{#  </li>#}
{#  {% endfor %}#}
{#</ul>#}
{#<form method="POST">#}
{#  <textarea name="note" id="note" class="form-control"></textarea>#}
{#  <br />#}
{#  <div align="center">#}
{#    <button type="submit" class="btn btn-primary">Add Note</button>#}
{#  </div>#}
{#</form>#}
{#{% endblock %}#}
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
    <br><br/>
<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="POST">
        <div class="mb-3 fw-bolder ">
          <label for="exampleFormControlInput1" class="form-label">Title*</label>
            <input type="text" class="form-control" id="title"  name="title" placeholder="Give Me a name ">
        </div>
        <div class="mb-3 fs-1">
          <label for="exampleFormControlTextarea1" class="form-label">Type Your Notes Below</label>
            <textarea class="form-control" name="note" id="note" rows="3"></textarea>
        </div>
        <div>
            <button type="submit" class="btn btn-outline-dark btn-lg">Add Note</button>
            <a href="/notes" class="btn btn-outline-dark btn-sm" id="edit" >Back</a>
        </div>
    </form>
</div>
{% endblock %}

Password_manager/website/templates/addpass.html
{% extends "base.html" %} {% block title %}Add Password{% endblock %} {% block content
%}
    <br><br/>
<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="POST">
      <div class="form-group">
        <label for="text">Website</label>
        <input
          type="text"
          class="form-control"
          id="url"
          name="url"
          placeholder="Website Url"
          value=""
        />
      </div>
      <div class="form-group">
        <label for="username">Username</label>
        <input
          type="text"
          class="form-control"
          id="username"
          name="username"
          placeholder="Username"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="psw"
          name="psw"
          data-toggle="password"
          data-placement="before"
          placeholder="Enter password"
        />
      </div>
      <br/>
        <div>
          <a  class="btn btn-secondary" onclick="Password()">Generate</a>
            <button  type="submit" class="btn btn-outline-dark btn-sm " id="edit" >Add</button>
        </div>
    </form>
</div>

    <i> <a href="/password" class="btn btn-outline-dark btn-sm fa fa-arrow-left" id="edit" >Back</a></i>
{% endblock %}

Password_manager/website/templates/base.html
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css"/>
    <link
      rel="stylesheet"
      href="../static/style.css"
    />
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body class="body1">
    {% include 'navbar.html' %}

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    <script src="https://kit.fontawesome.com/26570ac4fc.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js" crossorigin="anonymous"></script>

  </body>
</html>

Password_manager/website/templates/check.html
{% extends "base.html" %} {% block title %}Add Password{% endblock %} {% block content
%}
    <div class="container text-center" id="add">
      <div class="row">
        <div class="col">
      <h1>Check if your password is in a data breach</h1>
            <p>Pwned Passwords are hundreds of millions of real world passwords previously exposed in data breaches. This exposure makes them unsuitable for ongoing use as they're at much greater risk of being used to take over other accounts. They're searchable online below as well as being downloadable for use in other online systems. Read more about how HIBP protects the privacy of searched passwords.</p>
        </div>
      </div>
    </div>
    <br>
<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="POST">
        <br />
        <div class="form-group">
        <i class="fa-solid fa-key"></i>
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          data-toggle="password"
          data-placement="before"
          placeholder="Enter password"
        />
      </div>
      <br>
        <div>
      <button type="submit" class="btn btn-outline-dark btn-lg" onclick="check()">Check</button>
        </div>
    </form>
</div>
<div class="container" id="test1">
    <div class="container text-center">
      <div class="row">
        <div class="col">
          <h2>622</h2><br>
          <p>Hacked websites</p>
        </div>
        <div class="col">
         <h2>11,895,990,533</h2><br>
         <p>Hacked accounts</p>
        </div>
      </div>
    </div>
</div>
{% endblock %}

Password_manager/website/templates/disable_2fa.html
{% extends 'base.html' %}

{% block content %}
  <h1>Disable Two-Factor Authentication</h1>
  <p>
    To disable two-factor authentication, click the button below.
  </p>

  <form method="POST" action="{{ url_for('views.disable_2fa') }}">
    {{ form.csrf_token }}
    {{ form.submit(class='btn btn-danger') }}
  </form>
{% endblock %}

Password_manager/website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
    <br><br/>

<div class="card">
  <div class="card-header">
     {{ user.first_name }}
  </div>
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p class="card-text"><strong>Name:</strong>
    {{ user.first_name }}
    <br/>
    <strong>Email:</strong>
    {{ user.email }}
    <br/>
    <strong>Phone No:</strong>
    {{ user.phone_no }}
    <br/>
    <strong>Date joined:</strong>
        {{ user.date_added }}</p>
    <a href="{{ url_for('auth.index') }}" class="btn btn-outline-danger btn-sm">Logout</a>
    {% if not user.two_factor_enabled() %}
    <p><a href="/enable_2fa">Enable two-factor authentication</a></p>
    {% else %}
    <p><a href="/disable_2fa">Disable two-factor authentication</a></p>
    {% endif %}
  </div>
</div>


{% endblock %}

Password_manager/website/templates/index.html
<!DOCTYPE html>
<html lang="">

<head>
  <meta charset="utf-8">
  <title>Password Manager</title>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Ubuntu&display=swap" rel="stylesheet">


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <link rel="stylesheet" href="../static/style.css">



  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/26570ac4fc.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</head>


<body>

  <section id="title">

        <!-- Nav Bar -->
        <nav class="navbar navbar-expand-lg  ">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Password Manager</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="#about">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#services">Services</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#contact">Contact Me</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/login">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/signup">Signup</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>





        <!-- Title -->
      <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4">
              <h1>YOUR PASSWORD MANAGER AND MORE</h1>
              <p>From passwords to personal info, Password Manager is the simple solution for protecting all your data. Get started today.</p>
            </div>
            <div class="col-lg-4">
                <img src="../static/look.png" alt="iphone-mockup">
            </div>
        </div>
      </div>
  </section>


  <!-- Features -->
  <span id="services"></span>
  <section id="features">
    <div class="row">
        <div class="feature-box col-lg-3">
            <h3>Simplify your security</h3>
            <p>Enjoy seamless deployment, simple password management, and customizable security settings like 2FA and single sign-on </p>
        </div>
        <div class="feature-box col-lg-3">
            <h3>Generate random passwords</h3>
            <p>Generate random passwords for each of your accounts. Password cracking programs are designed to guess the most common passwords first, so completely random passwords will always be far stronger than those you come up with off the top of your head.</p>
        </div>
        <div class="feature-box col-lg-3">
            <h3>Store more than just passwords</h3>
            <p>Answers to security questions, shopping profiles, memberships, and medical prescriptions are just a few examples of additional information that can be stored securely in your password safe.</p>
        </div>
        <div class="feature-box col-lg-3">
            <h3>Pwned Passwords</h3>
            <p>Pwned Passwords are hundreds of millions of real world passwords previously exposed in data breaches. This exposure makes them unsuitable for ongoing use as they're at much greater risk of being used to take over other accounts. They're searchable online below as well as being downloadable for use in other online systems.</p>
        </div>
    </div>
  </section>


  <!-- Testimonials -->

  <section id="testimonials">
      <span id="about"></span>
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel" data-interval="2000">
          <div class="carousel-inner">
              <div class="carousel-item active">
                <h2>Cybersecurity continues to be one of the most strategically important issues in the digital world today and is also a field in which professionals are challenged by the fast pace in which technology and scenarios continue to change.</h2>
                <h3>We want this world to feel more secure and without the cost of freedom. Tips, tricks, news and articles about cybersecurity and more.</h3>
                <img class="about-page" src="../static/venki.jpeg" alt="Founder">
                <em>Founder,Bengalore, India</em>
              </div>
              <div class="carousel-item active">
                <h2>The focus of this site is the intersection of technology, privacy and freedom in the digital world. A site that covers general security topics (Manage Password, Secure Notes , Breached Passwords).</h2>
                <img class="about-page" src="../static/deepak.png" alt="Co-Founder">
                <em>Co-Founder Bengalore, India</em>
              </div>
          </div>
      </div>
  </section>

  <span id="contact"></span>
  <section id="contact_page">
    <section class="mb-4">
        <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
        <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
            a matter of hours to help you.</p>

        <div class="row">
            <div class="col-md-9 mb-md-0 mb-5">
                <form id="contact-form" name="contact-form" action="#" method="POST">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="md-form mb-0">
                                <label for="name" class="">Your name</label>
                                <input type="text" id="name" name="name" class="form-control">
                            </div>
                        </div>
                            <div class="col-md-6">
                                <div class="md-form mb-0">
                                    <label for="email" class="">Your email</label>
                                    <input type="text" id="email" name="email" class="form-control">
                                </div>
                            </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="md-form mb-0">
                                <label for="subject" class="">Subject</label>
                                <input type="text" id="subject" name="subject" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="md-form">
                                <label for="message">Your message</label>
                                <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            </div>
                        </div>
                     </div>
                </form>
                    <div class="text-center text-md-left">
                        <a class="btn btn-primary">Send</a>
                    </div>
                    <div class="status"></div>
            </div>
            <div class="col-md-3 text-center">
                <ul class="list-unstyled mb-0">
                    <li><i class="fas fa-map-marker-alt fa-2x"></i>
                        <p>Surana Collage South End Bangalore</p>
                    </li>

                    <li><i class="fas fa-phone mt-4 fa-2x"></i>
                        <p>+91 8073088890</p>
                    </li>

                    <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                        <p>allthingstech.tech</p>
                    </li>
                </ul>
            </div>
        </div>
    </section>
  </section>

  <footer id="footer">

    <p>© Copyright haveibeenpwned</p>

  </footer>


</body>

</html>

Password_manager/website/templates/note.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
    <br><br/>
<div class="shadow p-3 mb-5 bg-body rounded">
        <h2>{{ note_id.title }}</h2>
        Created on : {{ note_id.date }}<br><br/>
        <h6>{{ note_id.data }}</h6><br/>
        <a href="/notes" class="btn btn-outline-dark btn-sm" id="edit" >Back</a>
        <a href="/notes/edit/{{ note_id.id }}" class="btn btn-outline-dark btn-sm" id="edit" >Edit</a>
        <a href="/notes/delete/{{ note_id.id }}" class="btn btn-outline-danger btn-sm" id="delete" >Delete</a>
</div>
<br/>
{% endblock %}

Password_manager/website/templates/notes.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
    <a href="{{ url_for('views.add_notes') }}" class="btn btn-outline-dark btn-lg fa-solid fa-plus " id="add" >Add</a>
    {%  for note in notes %}
<div class="shadow p-3 mb-5 bg-body rounded">
        <h2><a href="/notes/{{ note.id }}" >{{ note.title }}</a></h2>
        Created on : {{ note.date }}<br><br/>
        <h6>{{ note.data }}</h6><br/>
        <a href="/notes/{{ note.id }}" class="btn btn-outline-dark btn-sm" id="edit" >View</a>
        <a href="/notes/edit/{{ note.id }}" class="btn btn-outline-dark btn-sm" id="edit" >Edit</a>
        <a href="/notes/delete/{{ note.id }}" class="btn btn-outline-danger btn-sm" id="edit" >Delete</a>
</div>
    {% endfor %}
{% endblock %}